name: Generate images for docs
on: [push]
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: setup.py

      - name: Install nf-core/tools
        run: pip install .

      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@main
        with:
          commit_changes: "true"
          clean_img_paths: docs/images/*.svg
